# This file was generated by GoReleaser. DO NOT EDIT.
class Ph < Formula
  desc "CLI tool to access the product hunt trending products"
  homepage "https://sibis.dev"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sibis/producthunt-cli/releases/download/v0.1.0/ph_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "34b1ecbad064e619964d3a92c7f18188ec54483c2f46627f352ba0e85746a8e3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sibis/producthunt-cli/releases/download/v0.1.0/ph_0.1.0_Linux_x86_64.tar.gz"
      sha256 "087214cf1f0a5dda9240d910cd49109af61cf79596022628d75b6bf7286231cf"
    end
  end

  def install
    bin.install "ph"
  end
end
