# This file was generated by GoReleaser. DO NOT EDIT.
class ProducthuntCli < Formula
  desc "CLI tool to access the product hunt trending products"
  homepage "https://sibis.dev"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sibis/producthunt-cli/releases/download/v0.1.0/producthunt-cli_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "f5b33b2babd8f635daf5a12c58f0f35179759ac8f9e8503b94166eaf816ba796"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sibis/producthunt-cli/releases/download/v0.1.0/producthunt-cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "54bfe6950e0486e1a26c969ec6ebb59d029fdf3ea1fd055ad85193d673858c47"
    end
  end

  def install
    bin.install "producthunt-cli"
  end
end
