# This file was generated by GoReleaser. DO NOT EDIT.
class ProducthuntCli < Formula
  desc "CLI tool to access the product hunt trending products"
  homepage "https://sibis.dev"
  version "v0.1.0-next"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/sibis/producthunt-cli/releases/download/v0.1.0/producthunt-cli_v0.1.0-next_Darwin_x86_64.tar.gz"
    sha256 "567159a86deeae02b387b014ccc87213b27b6edbe38700a73665cfd95d721b6d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/sibis/producthunt-cli/releases/download/v0.1.0/producthunt-cli_v0.1.0-next_Linux_x86_64.tar.gz"
      sha256 "782311edfe0617407a4732c6592cd2a541f46e3298b9b943385daf439fc02bbe"
    end
  end

  def install
    bin.install "producthunt-cli"
  end
end
